### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by baifeiajdj** [Asek3/sodium-1.12#17]
### Bug Description

can not creat new world

### Reproduction Steps

when creat new world then this bug appear and always constant produce crash-reports.

### Log File

[crash-2024-02-13_22.02.41-client.txt](https://github.com/Asek3/sodium-1.12/files/14267713/crash-2024-02-13_22.02.41-client.txt)
[crash-2024-02-13_22.02.41-server.txt](https://github.com/Asek3/sodium-1.12/files/14267715/crash-2024-02-13_22.02.41-server.txt)

**Comment by MCTian-mi** [comment]
I tested it and found it's gregtech that are causing the crash

**Comment by baifeiajdj** [comment]
> I tested it and found it's gregtech that are causing the crash
ok,i will report GTCEU

**Comment by baifeiajdj** [comment]
ok,i will report GTCEU

**Comment by MCTian-mi** [comment]
> ok,i will report GTCEU

I mean CEu+vintagium

**Comment by Asek3** [comment]
Alright, I'm getting into the issue, and... It should be addressed on the GregTech side, as it is still maintained by the developers. **Please, create an issue on their GitHub**

The problem lies in the fact that they use ASM to add their own RenderLayers and interfere with the vanilla chunk rendering. Vintagium is designed to work with the standard chunk rendering, hence the error.
The root of the issue can be found here -> https://github.com/GregTechCEu/GregTech/blob/master/src/main/java/gregtech/asm/visitors/RegionRenderCacheBuilderVisitor.java

**Comment by NostalgicLorikeet** [comment]
Can this be fixed by editing the vintagium-mixins file? I can't even tell if it's actually even implemented but I saw the file mentioned in another issue.
